In [1]:
# %matplotlib notebook
%matplotlib tk
import numpy as np 
import matplotlib.pyplot as plt 
import plotly
import plotly.graph_objects as go
import time
import math
from mpl_toolkits import mplot3d

tx1 = []
tx2 = []
ty = []
tm = 0

f = open("../ass1_data/data/q2/q2test.csv", "r")

for i in f:
    #print(x.strip())
    ''' a is matrix of m*2 size, where the first column is 1 '''
    i = i.strip()
    data = i.split(",")
    if(data[2]=="Y"):
        continue
    tx1.append(data[0])
    tx2.append(data[1])
    ty.append(data[2])
f.close()

In [2]:
m = 1000000
x1 = np.random.normal(3,2,1000000)
#plt.hist(x1, 30, density=True)

x2 = np.random.normal(-1,2,1000000)
print(x2.shape)
#plt.hist(x2, 30, density=True)

er = np.random.normal(0,math.sqrt(2),1000000)
#plt.hist(er, 30, density=True)

theta = np.array([3, 1, 2], dtype=float)
print(theta)
theta0 = np.full(1000000, theta[0])
print(theta0.shape)

y = theta0 + np.dot(theta[1], x1) + np.dot(theta[2], x2) + er

# plt.hist(y, 30, density=True)
# plt.show()

(1000000,)
[3. 1. 2.]
(1000000,)


In [3]:
print(x1.shape)

(1000000,)


In [4]:
x1[0]

3.8111465461246516

In [5]:
x0 = np.full(1000000, 1)
data = np.column_stack((x0,x1,x2,er))

In [6]:
data

array([[ 1.        ,  3.81114655, -4.79756804, -1.08749429],
       [ 1.        ,  4.57067862, -1.17583314, -1.95125709],
       [ 1.        ,  3.48323542,  1.49744017, -0.47371112],
       ...,
       [ 1.        ,  3.11826155,  0.55593032,  1.77452936],
       [ 1.        ,  1.59028961, -1.81813519,  1.14365157],
       [ 1.        ,  4.50208759, -2.6818617 , -0.91073217]])

In [7]:
np.random.shuffle(data)

In [8]:
data.shape

(1000000, 4)

In [9]:
y = theta0 + np.dot(theta[1], x1) + np.dot(theta[2], x2) + er
plt.hist(y, 30, density=True)

y = np.dot(theta[0], data[:,0]) + np.dot(theta[1], data[:,1]) + np.dot(theta[2], data[:,2]) + data[:,3]
# plt.hist(y, 30, density=True)
# plt.show()
print(theta.shape)
print(y.shape)

X = data[:,0:3].T
print(X.shape)
Y = y.reshape(1,m).astype(float)
print(Y.shape)
theta = np.zeros((3,1))
print(theta.shape)

(3,)
(1000000,)
(3, 1000000)
(1, 1000000)
(3, 1)


In [10]:
def calc_cost(X, Y, theta, i, r):
    s_i = i*r
    f_i = i*r + r - 1
    cost=np.dot(  theta.T.dot(X[:,s_i:f_i+1]) - Y[:,s_i:f_i+1] , ( theta.T.dot(X[:,s_i:f_i+1]) - Y[:,s_i:f_i+1] ).T )
    return cost[0,0]/(2*r)
def calc_cost_batch(X, Y, theta):
    cost=np.dot(  theta.T.dot(X) - Y , ( theta.T.dot(X) - Y ).T )
    return cost[0,0]/(2*X.shape[1])

In [11]:
# theta = np.array([0,0,0], dtype=float)
m = 1000000
r = 10000
num_batch = int(m/r)
rate = 0.001
stop = 0.00000000001
temp = np.array(theta)
cost_old = cost_new = -1
array_j=[]
array_theta=np.empty((0,3))
array_theta= np.append(array_theta,theta.T,axis=0)
theta_old=theta
error = 1
num_epoch = 0
num = 0
print(theta)
while(1):
    av_gd = 0
    for i in range(0, num_batch):
        
        
        s_i = i*r
        f_i = i*r + r - 1
        gd = rate * np.matmul(np.subtract(Y[:,s_i:f_i+1], np.matmul(theta.T, X[:,s_i:f_i+1])), X[:,s_i:f_i+1].T)
#         for j in range (0, r):
#             index = i*r+j
#             hx = np.dot(theta,data[index,0:3])
#             print(hx)
#             for k in range (0, theta.shape[0]):
#                 temp[k]+= rate*( y[index] - hx )*data[index,k]
        gd = gd/r
#         print(gd)
#             print(temp)
        theta_old = theta
        theta = np.add(theta, gd.T)
        
#         theta = theta + temp
        
        cost_old=cost_new
        cost_new = calc_cost(X,Y,theta,i,r)
        diff=abs(cost_new-cost_old)
        error=np.max(np.abs(theta - theta_old))
        errorp = error/np.max(theta)*100
        array_j.append(cost_new)
        array_theta= np.append(array_theta,theta.T,axis=0)
        av_gd += gd
#         print(len(array_theta))
#         print(cost_old,cost_new)
#         print(theta, np.max(gd))
    num_epoch += 1
    av_gd /= r
    av_gd = np.max(av_gd)
    print("num_epoch:",num_epoch)
    if(av_gd<stop):
        break
    
        #print(theta)

print("theta parameters:",theta)
print("rate:",rate," stopping condition:",stop)
print("Number of epochs:",num_epoch)
# plt.plot(range(0,len(array_j)),array_j)
# plt.show()
# print(theta)
# print(cost_new)

[[0.]
 [0.]
 [0.]]
num_epoch: 1
num_epoch: 2
num_epoch: 3
num_epoch: 4
num_epoch: 5
num_epoch: 6
num_epoch: 7
num_epoch: 8
num_epoch: 9
num_epoch: 10
num_epoch: 11
num_epoch: 12
num_epoch: 13
num_epoch: 14
num_epoch: 15
num_epoch: 16
num_epoch: 17
num_epoch: 18
num_epoch: 19
num_epoch: 20
num_epoch: 21
num_epoch: 22
num_epoch: 23
num_epoch: 24
num_epoch: 25
num_epoch: 26
num_epoch: 27
num_epoch: 28
num_epoch: 29
num_epoch: 30
num_epoch: 31
num_epoch: 32
num_epoch: 33
num_epoch: 34
num_epoch: 35
num_epoch: 36
num_epoch: 37
num_epoch: 38
num_epoch: 39
num_epoch: 40
num_epoch: 41
num_epoch: 42
num_epoch: 43
num_epoch: 44
num_epoch: 45
num_epoch: 46
num_epoch: 47
num_epoch: 48
num_epoch: 49
num_epoch: 50
num_epoch: 51
num_epoch: 52
num_epoch: 53
num_epoch: 54
num_epoch: 55
num_epoch: 56
num_epoch: 57
num_epoch: 58
num_epoch: 59
num_epoch: 60
num_epoch: 61
num_epoch: 62
num_epoch: 63
num_epoch: 64
num_epoch: 65
num_epoch: 66
num_epoch: 67
num_epoch: 68
num_epoch: 69
num_epoch: 70
num_epoch:

In [12]:
print(theta)

[[3.00363848]
 [0.99905013]
 [1.99920008]]


In [13]:
tm = len(ty)

tx1 = np.array(tx1).astype(float)
# tx1 = (tx1 - np.mean(tx1)) / (np.std(tx1))

tx2 = np.array(tx2).astype(float)
# tx2 = (tx2 - np.mean(tx2)) / (np.std(tx2))
tx0 = np.full(tm, 1)
# print(x0)

ty=np.array(ty).astype(float)

In [14]:
tX=np.column_stack((tx0,tx1,tx2)).T
tY=ty.reshape(10000,1).T

print(tX.shape, tY.shape)

(3, 10000) (1, 10000)


In [15]:
theta_orig = np.array([3,1,2]).reshape(3,1).astype(float)
print(theta_orig,theta_orig.shape)

[[3.]
 [1.]
 [2.]] (3, 1)


In [16]:
cost_lern_para = calc_cost_batch(tX,tY,theta)
cost_orig_para = calc_cost_batch(tX,tY,theta_orig)
print("rate:",rate)
print("stopping condition:",stop)
print("cost with learnt parameters:",cost_lern_para)
print("cost with original parameters:",cost_orig_para)

rate: 0.001
stopping condition: 1e-11
cost with learnt parameters: 0.9831762998827508
cost with original parameters: 0.9829469214999997


In [17]:
# print(calc_cost(tX,tY,theta,0,tm))

In [18]:
print(array_theta.shape)
print(np.max(array_theta[:,1]))
# num_rows_theta_arr=array_theta.shape[0]//3
# t=np.resize(array_theta,(num_rows_theta_arr,3))
print(array_theta)
# print(t.shape)
t = array_theta
fig=plt.figure()
ax = plt.axes(projection='3d')
ax.set_xlabel('theta(0)')
ax.set_ylabel('theta(1)')
ax.set_zlabel('theta(2)')
ax.set_xlim(0,np.max(array_theta[:,0]))
ax.set_ylim(0,np.max(array_theta[:,1]))
ax.set_zlim(0,np.max(array_theta[:,2]))

for i in range(0, t.shape[0], 20):
    ax.plot3D(t[0:i,0],t[0:i,1],t[0:i,2],'gray')
    plt.pause(0.02)
    
# print(t[:,0].shape)

plt.show()

(49901, 3)
1.4603196291521232
[[0.         0.         0.        ]
 [0.00392617 0.01583381 0.00383552]
 [0.00784388 0.03173165 0.00783587]
 ...
 [3.00364459 0.99906004 1.99911001]
 [3.00365757 0.99911511 1.99910231]
 [3.00363848 0.99905013 1.99920008]]


TclError: can't invoke "update" command: application has been destroyed